export const ADD_USER_INFO = 'ADD_USER_INFO';
export const LOGOUT_USER = 'LOGOUT_USER';

export const CREATE_PRESENTATIONS_SUCCESS = 'CREATE_PRESENTATIONS_SUCCESS';
export const LOAD_PRESENTATIONS_SUCCESS = 'LOAD_PRESENTATIONS_SUCCESS';

export const GET_SLIDES = 'GET_SLIDES';
export const UPDATE_SLIDE = 'UPDATE_SLIDE';